### ISSUE TITLE
kw_defaults error with values from the top scope

### ISSUE THREAD

**Issue by acbart** [skulpt/skulpt#1132]
I believe this is an issue present in the core, but it's possible that it's caused by something on my AST branch. For now, I wanted to make the note here.

```python
class Test:
    def x(self, *, y=ValueError):
        pass
```

The code above generates the traceback below:

```
UNCAUGHT EXCEPTION: Error: Assertion failure
Error: Assertion failure
    at Object../src/assert-dev.js.Sk.asserts.assert (C:\Users\acbart\Projects\blockpy-edu\skulpt_dev\dist\skulpt.js:6094:15)
    at Compiler../src/compile.js.Compiler.nameop (C:\Users\acbart\Projects\blockpy-edu\skulpt_dev\dist\skulpt.js:15830:16)
    at Compiler../src/compile.js.Compiler.vexpr (C:\Users\acbart\Projects\blockpy-edu\skulpt_dev\dist\skulpt.js:14208:25)
    at args.kw_defaults.map.e (C:\Users\acbart\Projects\blockpy-edu\skulpt_dev\dist\skulpt.js:15102:58)
    at Array.map (<anonymous>)
    at Compiler../src/compile.js.Compiler.buildcodeobj (C:\Users\acbart\Projects\blockpy-edu\skulpt_dev\dist\skulpt.js:15102:40)
    at Compiler../src/compile.js.Compiler.cfunction (C:\Users\acbart\Projects\blockpy-edu\skulpt_dev\dist\skulpt.js:15432:22)
    at Compiler../src/compile.js.Compiler.vstmt (C:\Users\acbart\Projects\blockpy-edu\skulpt_dev\dist\skulpt.js:15670:18)
    at Compiler../src/compile.js.Compiler.cbody (C:\Users\acbart\Projects\blockpy-edu\skulpt_dev\dist\skulpt.js:15974:14)
    at Compiler../src/compile.js.Compiler.cclass (C:\Users\acbart\Projects\blockpy-edu\skulpt_dev\dist\skulpt.js:15589:10)
```

As far as I can tell, something about how `kw_defaults` is being treated is wrong, with the end result that the `scope` in `nameop` gets the value 0. I haven't looked into the what and the why, but since you can avoid this issue by removing the asterisk in the code, I'm pretty sure it's something wrong with keyword-only arguments.

**Comment by s-cork** [comment]
Same code on master seems to compile fine...

**Comment by acbart** [comment]
Must be something dumb on my local, or perhaps I had some bug I snagged between PRs commits. I keep merging in new changes, and you keep making more. I'll close this for now.

**Comment by acbart** [comment]
Okay, am I crazy? I just did a fresh clone and was able to reproduce this error. It seems to be a result of using varargs and then following it with a default value that captures a variable from the top-level module scope. If I reference the variable in the class scope, then it is available. But it doesn't seem like it's making it available if it's just on the function argument scope IF you have a vararg.

**Comment by acbart** [comment]
OKAY.

Pretty sure that this code:

```javascript
if (s.args.kw_defaults) {
    this.SEQExpr(s.args.kw_defaults);
}
```

Is needed around here: https://github.com/skulpt/skulpt/blob/e87e5eb68f264314c5e3cdbec30b6d7b3c9b1ce0/src/symtable.js#L489-L494

Basically, when you have varargs, the parser puts the default values into the `kw_defaults` field. If you don't, then all defaults go into the `defaults` field.

**Comment by s-cork** [comment]
Sorry I must have used `npm run build` and so assertion errors were switched off 🤦 . In `dev` I get the same assertion failure.

But the original code snippet does seem to compile and works as expected when asserts are off??
