### ISSUE TITLE
a bug for super when inherit multi classes with same method

### ISSUE THREAD

**Issue by alexwenbj** [skulpt/skulpt#1161]
See the code below:
```
class A:
	def a(self):
		print("a in class A")

class B:
	def a(self):
		print("a in class B")

class C(B, A): #<-- attention this order
	def c(self):
		self.a()
	def d(self):
		super(B,self).a()  #<--attention this line

c = C()
c.c()
c.d()
```
In CPython,it works fine:
```
a in class B
a in class A
```
In Skulpt:
```
a in class B
Line 13 : 'super' object has no attribute 'a'
```
If I change the order of inheritance of C from:
`class C(B, A) `
to 
`class(A, B)`
CPython will raise the same error:'super' object has no attribute 'a':
```
a in class A
Traceback (most recent call last):
  File "p.py", line 17, in <module>
    c.d()
  File "p.py", line 13, in d
    super(B,self).a()
AttributeError: 'super' object has no attribute 'a'
```

**Comment by s-cork** [comment]
this seems to be a problem with how `super` finds the `'next in line'`. 

The skulpt algorithm doesn't follow cpython's algorithm and in the example that breaks the skulpt algorithm finds the `'next in line'` (after `B`) from `B`'s perspective rather than from `C`'s perspective... so of course from `B`'s perspective the `'next in line'` is `object` but from `C`'s perspective the `'next in line'` is `A`...

I've fixed this in #1092 

https://github.com/s-cork/skulpt/blob/8807132080322835085bb06276249b1b05b68d92/src/super.js#L41

To fix this on master the `tp$getattr` for `super_` would need to change to be in line with Cpython's algorithm.
