### ISSUE TITLE
Build failure in wrapmodules/minify stage

### ISSUE THREAD

**Issue by bennorth** [skulpt/skulpt#1231]
I can't pin down exactly when this started happening, but just now a fresh clone fails to build for me:
```shell
% git clone https://github.com/skulpt/skulpt.git skulpt-build-test
[... normal output ...]
% cd skulpt-build-test
% npm install
[... no obvious errors ...]
% npm run build
[...]
> node support/build/wrapmodules.js builtin

/tmp/skulpt-build-test/node_modules/@babel/core/lib/transformation/index.js:45
    throw e;
    ^

TypeError: unknown: Cannot read property 'bindings' of null
    at PluginPass.enter (/tmp/skulpt-build-test/node_modules/babel-plugin-minify-simplify/lib/index.js:331:44)
    at newFn (/tmp/skulpt-build-test/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/tmp/skulpt-build-test/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/tmp/skulpt-build-test/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/tmp/skulpt-build-test/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/tmp/skulpt-build-test/node_modules/@babel/traverse/lib/context.js:115:16)
    at TraversalContext.visitQueue (/tmp/skulpt-build-test/node_modules/@babel/traverse/lib/context.js:121:21)
    at TraversalContext.visitMultiple (/tmp/skulpt-build-test/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/tmp/skulpt-build-test/node_modules/@babel/traverse/lib/context.js:141:19)
    at Function.traverse.node (/tmp/skulpt-build-test/node_modules/@babel/traverse/lib/index.js:82:17) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```
There was [an update to `@babel/core` at 2020-11-20T21:06:00.584Z](https://www.npmjs.com/package/@babel/core/v/7.12.7) which might be relevant.

I have reproduced the above failure on an Amazon Lightsail instance (Ubuntu 20.04LTS image) with fresh node/npm installation, so I don't think it's a quirk of my setup here.

I looked into this a bit, and came across [terser](https://www.npmjs.com/package/terser), which seems more active than `babel-minify`.  There were some changes required to `wrapmodules.js` to use `terser`, in the way `terser` specifies options, and the fact that it's async.  With these changes, I was able to get a minified build which passed all unit tests, with the exception of `TimeTestCase.test_strftime`, which failed with `Expected Jan 01 1970 02:01:01 to equal Jan 01 1970 01:01:01`.  I don't think this is relevant, as an old build environment I have does build current `master` successfully, and fails the same unit test.

I will make a PR for using `terser`, but I realise that changing the minify tool would be quite a deep change.  I might well have overlooked a simpler solution!

**Comment by bennorth** [comment]
In case node/npm versions are relevant, I saw the failure with:
```shell
% node --version
v12.19.0
% npm --version
6.14.8
```
and
```shell
% node --version
v14.15.1
% npm --version
6.14.8
```
and also
```
% node --version
v10.23.0
% npm --version
6.14.8
```
(the versions I see Travis uses).

**Comment by bennorth** [comment]
Trying again just now, Skulpt runs `npm run build` fine in a fresh checkout.  I see there have been two further [@babel/core](https://www.npmjs.com/package/@babel/core) releases since the one which perhaps broke Skulpt, so maybe this PR can be closed as having been overtaken by events.
