### ISSUE TITLE
Can't build skulpt

### ISSUE THREAD

**Issue by gresm** [skulpt/skulpt#1462]
I can't build skulpt with ``Node.js v18.4.0``

When running
```bash
npm install
```
I get this output:
```
added 618 packages, and audited 619 packages in 9s

14 vulnerabilities (2 moderate, 12 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
Running ```npm audit``` or ```npm audit --force``` doesn't change anything.
Assuming that everyting went good in the step before, I tried running ```npm run build```, but I got this error:
```
> skulpt@1.2.0 prebuild
> node support/build/wrapmodules.js internal

wrapmodules done

> skulpt@1.2.0 build
> webpack --mode production

WARNING: Working directory is not clean.
/skulpt/node_modules/loader-runner/lib/LoaderRunner.js:133
		if(isError) throw e;
		            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/skulpt/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/skulpt/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/skulpt/node_modules/webpack/lib/NormalModule.js:471:10)
    at /skulpt/node_modules/webpack/lib/NormalModule.js:503:5
    at /skulpt/node_modules/webpack/lib/NormalModule.js:358:12
    at /skulpt/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/skulpt/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/skulpt/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /skulpt/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/skulpt/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at module.exports (/skulpt/node_modules/eslint-loader/index.js:274:11)
    at LOADER_EXECUTION (/skulpt/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/skulpt/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/skulpt/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/skulpt/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/skulpt/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /skulpt/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /skulpt/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
```

**Comment by Dustyposa** [comment]
Maybe you can try downgrade your node version.

**Comment by gresm** [comment]
@Dustyposa what latest version of node.js you can verify that works?

**Comment by gresm** [comment]
Update: According to https://stackoverflow.com/a/69719852/15140144 setting ``NODE_OPTIONS`` environment variable to: ``--openssl-legacy-provider`` should work.

**Comment by bnmnetp** [comment]
I have recently built skulpt with node 18.7.0 and have had no issues with tests passing or it working in the browser.

**Comment by gresm** [comment]
Update:
I've successfully built skulpt using these commands (with node v18.4.0):
```sh
git clone https://github.com/skulpt/skulpt.git
cd skulpt
npm install
NODE_OPTIONS=--openssl-legacy-provider && npm run dist
```
It would be useful if there were any mention about it in building section.

**Comment by bnmnetp** [comment]
I'm not sure what I would mention.  This seems like a node problem or a problem with node in your particular environment.  Not something particular to skulpt.

**Comment by gresm** [comment]
No @bnmnetp , this is an issue with skulpt: it depends on deprecated and vulnerable versions of packages, such as webpack. This is at least an issue with never versions of node. If you don't have plans on supporting them, at least specify what versions are supported.
