### ISSUE TITLE
cannot build skulpt

### ISSUE THREAD

**Issue by acekingke** [skulpt/skulpt#742]
run: 562/562 (+1 disabled)
Quitting
Running jshint
Traceback (most recent call last):
  File "skulpt.py", line 1409, in <module>
    main()
  File "skulpt.py", line 1326, in main
    dist(options)
  File "skulpt.py", line 742, in dist
    ret = test()
  File "skulpt.py", line 234, in test
    jshintcmd = "jshint {1}".format(' '.join(files))
IndexError: tuple index out of range

**Comment by BradChan** [comment]
I have the same issue.

**Comment by albertjan** [comment]
Are you using python 2?
