### ISSUE TITLE
regenparser not working

### ISSUE THREAD

**Issue by rixner** [skulpt/skulpt#882]
While I was trying to move functionality away from skulpt.py and into node.js, I found that ```regenparser``` seems to be broken:

```
$ ./m regenparser
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    pgen.generate_grammar().genjs()
  File "/home/rixner/github/skulpt/src/pgen/parser/pgen.py", line 383, in generate_grammar
    p = ParserGenerator(filename)
  File "/home/rixner/github/skulpt/src/pgen/parser/pgen.py", line 21, in __init__
    self.dfas, self.startsymbol = self.parse()
  File "/home/rixner/github/skulpt/src/pgen/parser/pgen.py", line 154, in parse
    self.expect(token.OP, ":")
  File "/home/rixner/github/skulpt/src/pgen/parser/pgen.py", line 316, in expect
    type, value, self.type, self.value)
  File "/home/rixner/github/skulpt/src/pgen/parser/pgen.py", line 335, in raise_error
    self.end[1], self.line))
  File "Grammar.txt", line 30
    single_input: NEWLINE | simple_stmt | compound_stmt NEWLINE
                ^
SyntaxError: expected 51/:, got 52/:
```
This is in ```master```.  I didn't look at how far back the problem goes.

**Comment by albertjan** [comment]
We got this fixed in our py3k branch

**Comment by rixner** [comment]
When do the rest of us get to benefit from your  py3k branch? :smile:

**Comment by rixner** [comment]
@albertjan any hints about how you fixed regenparser?  I looked [here](https://github.com/trinketapp/skulpt/tree/py3k) and regenparser doesn't seem to work there, either (unless I'm missing something)...

**Comment by meredydd** [comment]
> When do the rest of us get to benefit from your py3k branch? :smile: 

Now! Take a look at PR #905 :-D

(Sorry, we'd moved work from Trinket's repo to mine)-
