### ISSUE TITLE
Fresh build triggers deprecation errors with nmber?

### ISSUE THREAD

**Issue by acbart** [skulpt/skulpt#912]
I just cloned a new fork of Skulpt and tried to build a fresh copy:

    > git clone .../skulpt
    > cd skulpt/
    > npm install
    > npm run build

This triggered a bunch of build errors, apparently related to the deprecation of the nmber module. I've attached the log.

Is there some other way I should be building the library? For reference, this is on Windows.

[skulpt_nmber_error.log](https://github.com/skulpt/skulpt/files/3306316/skulpt_nmber_error.log)

**Comment by acbart** [comment]
I believe the offending line of code is from time.js: https://github.com/skulpt/skulpt/blob/master/src/lib/time.js#L265

Perhaps uncovered/caused by the work being done over there. Changing the relevant line to:

    mod.accept2dyear = Sk.builtin.assk$(1, Sk.builtin.int_);

seems to have fixed it. It's taking a *long* time to do my build, however, so I will have to let you know. I think I'm past 10 minutes now?

**Comment by acbart** [comment]
Ah, this is happening with build, but not devbuild. I'm guessing we're not there yet with the new version?

**Comment by albertjan** [comment]
this doesn't happen for me what version of node are you on?

**Comment by albertjan** [comment]
Travis runs all builds fine.

**Comment by bnmnetp** [comment]
@acbart -- maybe a windows thing going on.  build, and diet run fine on macOS.  A clean install on a fresh DO droplet works fine as well.  As @albertjan points out our Travis-CI builds use the same build infrastructure and they are all passing.

**Comment by acbart** [comment]
My node was 6.10.1, so super out-of-date. After updating, I'm now on 12.4.0, but it's still causing the same issue.

**Comment by albertjan** [comment]
@acbart can you remove your `node_modules` and reinstall?

**Comment by acbart** [comment]
Still seems to be present after removing node_modules and reinstalling. 

Just to let myself move forward, I removed number.js from the main.js, got rid of its remaining references in time.js, processing.js, and env.js, and deleted the file. That seems to have either caused or uncovered a new, more cryptic error:

    ERROR in Unexpected token u in JSON at position 0

I've attached the log, will continue to investigate.

[skulpt_unicode_u_error.log](https://github.com/skulpt/skulpt/files/3306588/skulpt_unicode_u_error.log)

**Comment by acbart** [comment]
Okay, the unicode U thing (something trying to parse an undefined value) error is actually an issue with google closure on windows: https://github.com/webpack-contrib/closure-webpack-plugin/issues/95

I removed the minimizer array in there, and it builds (though I'm not sure I'm getting any benefit over the dev build).

**Comment by rixner** [comment]
@acbart in ```webpack.config.js``` if you look in the ```ClosureWebpackPlugin``` options you should see ```deprecated``` in ```jscomp_off```, which should have turned off those deprecated warnings so you could leave ```number.js```.  I see now, though, that I screwed up and ```deprecated``` is also in ```jscomp_error```.  Can you remove ```deprecated``` from ```jscomp_error``` and see if that allows you to not have to delete ```number.js```?  It obviously won't solve the unicode issue, but it would be good to get Windows on the same page with the closure compiler options.

**Comment by acbart** [comment]
Yes! That seems to have fixed it. Still getting the unexpected token error, as you thought, but at least that seems to be a separate issue. And it's not super convenient that the build process takes 117 seconds to run, but I suppose that's what `watch` will be for.

**Comment by rixner** [comment]
It only takes about 9 seconds on my machine.   I suspect that you are using the javascript closure compiler instead of the java one.  Can you confirm by looking at your installed npm packages?

This is what I have:

```
$ npm list | grep "closure"
├─┬ closure-webpack-plugin@2.0.1
├─┬ google-closure-compiler@20190415.0.0
│ ├── google-closure-compiler-java@20190415.0.0
│ ├── google-closure-compiler-js@20190415.0.0
│ ├── google-closure-compiler-linux@20190415.0.0
│ ├── UNMET OPTIONAL DEPENDENCY google-closure-compiler-osx@20190415.0.0
```

I suspect you're going to see ```UNMET OPTIONAL DEPENDENCY google-closure-compiler-java@20190415.0.0```.  If you can get the Java one installed things will be much, much faster.

**Comment by acbart** [comment]
Hm, sounds promising. This is what I see, which suggests Windows will be making my life harder per usual:

```
+-- closure-webpack-plugin@2.0.1
+-- google-closure-compiler@20190415.0.0
| +-- google-closure-compiler-java@20190415.0.0
| +-- google-closure-compiler-js@20190415.0.0
| +-- UNMET OPTIONAL DEPENDENCY google-closure-compiler-linux@20190415.0.0
| +-- UNMET OPTIONAL DEPENDENCY google-closure-compiler-osx@20190415.0.0
```

**Comment by rixner** [comment]
I just added the webpack fix for ```deprecated``` to #911.

**Comment by rixner** [comment]
@acbart well at least you have the Java version installed.  I'm not sure how you can check which closure compiler is actually running, though (```-java``` vs ```-js```)...  I suppose it may also be the case that the ```-linux``` and ```-osx``` versions work faster?  I have no idea.

**Comment by rixner** [comment]
@acbart can you try explicitly setting the ```platform``` to ```java``` in the ```ClosureWebpackPlugin``` (https://github.com/webpack-contrib/closure-webpack-plugin) in your webpack config and see what that does?  It's possible it's not finding your Java installation, so is falling back to the JS compiler...

**Comment by acbart** [comment]
Yes, I'm on the same page with that fix - trying it now, but it's causing a different kind of error that I'm looking into now. Might be my paths, might be something else...

```
ERROR in closure-compiler: java.nio.file.InvalidPathException: Illegal char <?> at index 91: C:\Users\acbart\Projects\bl
ockpy-edu\skulpt\node_modules\webpack-jshint-loader\lib\index.js??ref--4-0!C:\Users\acbart\Projects\blockpy-edu\skulpt\n
ode_modules\eslint-loader\index.js!C:\Users\acbart\Projects\blockpy-edu\skulpt\src\main.js
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at sun.nio.fs.AbstractPath.resolveSibling(Unknown Source)
        at com.google.javascript.jscomp.SourceMapResolver.getRelativePath(SourceMapResolver.java:102)
        at com.google.javascript.jscomp.Compiler.addSourceMapSourceFiles(Compiler.java:2805)
        at com.google.javascript.jscomp.Compiler.initBasedOnOptions(Compiler.java:541)
        at com.google.javascript.jscomp.Compiler.initModules(Compiler.java:511)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1207)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:518)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2168)
```

**Comment by rixner** [comment]
I don't know that this will necessarily fix it, but get rid of the jshint loader (as per #911), as that will be one less thing monkeying with the files.

**Comment by acbart** [comment]
That gets rid of the issue that it has with the "?", but now it's complaining about the ":" from the second path. Curious that it has paths separated by "!" characters, I'm going to read up on Closure and see what's going on there. I also tried turning off eslint, and that allows things to go through - much better performance at about 16 seconds. So now I just need to figure out how to keep eslint from clogging things up.

```
ERROR in closure-compiler: java.nio.file.InvalidPathException: Illegal char <:> at index 81: C:\Users\acbart\Projects\bl
ockpy-edu\skulpt\node_modules\eslint-loader\index.js!C:\Users\acbart\Projects\blockpy-edu\skulpt\src\main.js
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at sun.nio.fs.AbstractPath.resolveSibling(Unknown Source)
        at com.google.javascript.jscomp.SourceMapResolver.getRelativePath(SourceMapResolver.java:102)
        at com.google.javascript.jscomp.Compiler.addSourceMapSourceFiles(Compiler.java:2805)
        at com.google.javascript.jscomp.Compiler.initBasedOnOptions(Compiler.java:541)
        at com.google.javascript.jscomp.Compiler.initModules(Compiler.java:511)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1207)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:518)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2168)
```

**Comment by rixner** [comment]
I suspect it's something to do with webpack, not necessarily the closure compiler itself.  Other people see that related to source maps (https://github.com/google/closure-compiler/issues/2776).

**Comment by acbart** [comment]
Yeah, I think it has something to do with how the webpack plugin is passing along the source file to closure. For some reason it thinks it needs to concatenate the two JS files with "!"?

**Comment by acbart** [comment]
I'm still up against a wall here with this issue. It seems like Webpack is dead-set on concatenating all loaders onto the actual entry point, and it seems like the Closure Compiler in Java mode is not happy with exclamation marks being in the path passed in. The linked issue was about a distinctive error with source maps, so it doesn't seem to apply. I've filed an issue with the Closure Compiler Plugin folks, but I don't know that it's their problem (https://github.com/webpack-contrib/closure-webpack-plugin/issues/100). My naive thought is that the URL being passed into the closure compiler is wrong.

On the plus side, this does seem like the last barrier I have to getting the compiler to work, and I can still do a devbuild. Frustrating not to be able to actually build this new version, though.

**Comment by rixner** [comment]
If you completely remove the eslint loader does it work?  We need/want that to enforce style, but it's not contributing to the actual build.

**Comment by acbart** [comment]
Yep, works just fine once that's gone. But I agree that enforcing the style is important - it's helped me catch a few things. For my local purposes I can turn it off when I want to do a production build, but hopefully long term there can be a proper fix.

**Comment by rixner** [comment]
Well, we could decouple style checking from building, i.e.,  ```npm run checkstyle```.  It's nice to have it in the webpack build simply because that ensures all the right files run through it, regardless of any other changes to how the code is split up.  But, it's not strictly necessary, as we could just run eslint on ```src/*.js``` or something.

**Comment by rixner** [comment]
(Though I don't know how to make sure that ```src/*.js``` becomes ```src\*.js``` for windows in package.json...)

**Comment by acbart** [comment]
In my experience, forward slashes usually work just as well as blackslashes. I typically avoid backslashes where possible on Windows.
