### ISSUE TITLE
skuplt failed to use pygal

### ISSUE THREAD

**Issue by Lifan1998** [skulpt/skulpt#923]
The latest skuplt failed to introduce pygal, but it was correct before (about skuplt in March).

My pygal.js:  https://github.com/trinketapp/pygal.js

Error:
```
Sk.builtin.ExternalError {nativeError: TypeError: a.$jsstr is not a function...
```
```
"TypeError: a.$jsstr is not a function
    at e.Sk.builtin.object.GenericGetAttr (http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:116:503)
    at Sk.builtin.object.GenericPythonGetAttr (http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:118:426)
    at Sk.builtin.func.tp$call (http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:141:230)
    at Sk.builtin.method.tp$call (http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:213:447)
    at Object.Sk.misceval.applyOrSuspend (http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:245:17)
    at Object.Sk.misceval.callsimOrSuspendArray (http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:238:317)
    at http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:72:484
    at Object.Sk.misceval.tryCatch (http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:242:132)
    at e.tp$getattr (http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:72:445)
    at eval (eval at <anonymous> (http://106.14.141.90/js/skulpt-1.0.0/skulpt.min.js:935:229), <anonymous>:1:1333)"
```

My  dependence on production environment:
```
export const externalLibs = {
    'src/builtin/pygal/__init__.js': {
        path: 'https://assets.baydn.com/baydn/public/pygal/1.0.0/__init__.js',
        dependencies: [
            'https://assets.baydn.com/baydn/public/highcharts/7.1.1/highcharts.js',
            'https://assets.baydn.com/baydn/public/highcharts/7.1.1/highcharts-more.js',
        ],
    },
};
```

**Comment by albertjan** [comment]
@Lifan1998 the `externalLibs` functionality has been removed, you can implement something similar expanding on your implementation of the `read` function you pass to `Sk.configure`.  Have a look at these issues: https://github.com/skulpt/skulpt/issues/855 and https://github.com/skulpt/skulpt/issues/863. The other problem is a breaking change that will require an update of https://github.com/trinketapp/pygal.js which is on my list 😄

**Comment by Lifan1998** [comment]
@albertjan Thank you for your reply. 
I have used Sk.configure.
```
Sk.configure({
        ...,
        read: builtinRead,
        __future__: Sk.python3,
});
const builtinRead = x => {
        ......
        if (!files[fileName] && fileName in externalLibs) {
            return Sk.misceval.promiseToSuspension(
                fetchDeps(fileName).then(() => fetchExternalLib(externalLibs[fileName].path)),
            );
        }
        ......
};
```

So this problem may be caused by pygal.js？When can you update pygal.js? Or can you tell me how to modify pygal.js?

**Comment by albertjan** [comment]
pygal is broken because of this change: https://github.com/skulpt/skulpt/pull/859

**Comment by Dustyposa** [comment]
@Lifan1998 
Can you normal use `pygal` in project? I have same problem in my project. 
`$jsstr` not a function.

**Comment by Lifan1998** [comment]
@Dustyposa https://github.com/Lifan1998/pygal.js

**Comment by Lifan1998** [comment]
@Dustyposa 
Please upgrade carefully, I have encountered a lot of compatibility issues, such as oppoR9, MI8 and so on. If you can use it in production environment, please contact me at 2224779926@qq.com.

**Comment by Dustyposa** [comment]
@Lifan1998 Oh,I'm not use pygal. I used other externalLib, emmm and I don't know how to solve `$jsstr`. Why cause this error?

**Comment by Lifan1998** [comment]
@Dustyposa
It is broken because of this change: [#859](https://github.com/skulpt/skulpt/pull/859) 

The solution is to use python string object instead of jsname.

Please refer to this [commit](https://github.com/Lifan1998/pygal.js/commit/7bbd0dd9c5784b17a2167ac89b8e64d1677b4e16)

**Comment by Dustyposa** [comment]
@Lifan1998 Thanks.I solve `$jsstr` error.And I meet a 'Promise error'.How can I make a `Suspension` task, to be a normal task? And I send an email for u, did you received it?

**Comment by Lifan1998** [comment]
Right.I have already replied to you on outlook email.

I have not encountered 'Promise error'.
