### ISSUE TITLE
 npm run dist error  and npm run build error

### ISSUE THREAD

**Issue by yzxnwj** [skulpt/skulpt#957]
please tell me   how to build 
I need to support this syntax   print('2,4,6',end="@")  print('hello')
How do I need to change that file

                                                        Thanks

**Comment by wensonH** [comment]
@yzxnwj Firstly. are there two print statement in one line? if there are you should add semicolon at the end of the first print: eg: print('2,4,6', end="@");print("hello"). 

Secondly, what's your error message after you run "npm run dist "？

**Comment by yzxnwj** [comment]
ERROR in closure-compiler: java.nio.file.InvalidPathException: Illegal char <:> at index 67: C:\MyProcedure\skulpt4\skulpt\node_modules\eslint-loader\index.js!C:\MyProcedure\skulpt4\skulpt\src\main.js
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at sun.nio.fs.AbstractPath.resolveSibling(Unknown Source)
        at com.google.javascript.jscomp.SourceMapResolver.getRelativePath(SourceMapResolver.java:102)
        at com.google.javascript.jscomp.Compiler.addSourceMapSourceFiles(Compiler.java:2805)
        at com.google.javascript.jscomp.Compiler.initBasedOnOptions(Compiler.java:541)
        at com.google.javascript.jscomp.Compiler.initModules(Compiler.java:511)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1207)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:518)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2168)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! skulpt@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the skulpt@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\17621\AppData\Roaming\npm-cache\_logs\2019-09-07T03_46_20_828Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! skulpt@1.0.0 dist: `npm run build && npm run test && npm run doc && node support/build/copy2docs.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the skulpt@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\17621\AppData\Roaming\npm-cache\_logs\2019-09-07T03_46_20_880Z-debug.log

**Comment by wensonH** [comment]
@yzxnwj I have the same error too，but I don't have a solution. According to the err msg, I guess it maybe  uncompatible with 'windows path' in compiler.jar? I try it on linux, and found that it run without this error.

**Comment by yzxnwj** [comment]
thanks Let me try to run it on Linux
